import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# ensure app modules are importable
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from config import settings
import models  # noqa: F401 — registers all SQLModel tables
from sqlmodel import SQLModel

config = context.config
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = SQLModel.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def render_item(type_, obj, autogen_context):
    """Ensure autogenerated migrations import sqlmodel for AutoString columns —
    without this, `alembic revision --autogenerate` emits sqlmodel.sql.sqltypes
    references without the import, which fails at migration time."""
    if type_ == "type" and type(obj).__module__.startswith("sqlmodel"):
        autogen_context.imports.add("import sqlmodel")
    return False


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,  # required for SQLite ALTER TABLE support
            render_item=render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
