"""add_edit_feedback_and_profile_photo

Revision ID: 919b096e9247
Revises: 
Create Date: 2026-05-04 15:58:44.614554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '919b096e9247'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # edit_feedback table may already exist from SQLModel auto-create
    conn = op.get_bind()
    existing = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='edit_feedback'")).fetchone()
    if not existing:
        op.create_table(
            'edit_feedback',
            sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), primary_key=True),
            sa.Column('profile_id', sqlmodel.sql.sqltypes.AutoString(), sa.ForeignKey('candidate_profile.id'), nullable=False, index=True),
            sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), sa.ForeignKey('generation_run.id'), nullable=False),
            sa.Column('run_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('field_context', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('original_value', sa.Text(), nullable=False),
            sa.Column('edited_value', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
        )

    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.alter_column('job_description_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('application_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_run', schema=None) as batch_op:
        batch_op.alter_column('application_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('job_description_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('candidate_profile', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    # ### end Alembic commands ###
