"""add job_lead starts_at

Revision ID: e7c2002bcb00
Revises: cc6a8389cb43
Create Date: 2026-08-03 02:12:23.479613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e7c2002bcb00'
down_revision: Union[str, Sequence[str], None] = 'cc6a8389cb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_lead', schema=None) as batch_op:
        batch_op.drop_column('starts_at')

    # ### end Alembic commands ###
